client lan {
    ipaddr          = 172.21.0.0/24
    secret          = testing123
    shortname       = ville-lan
    nas_type        = other
}

client dmz {
    ipaddr          = 172.20.0.0/24
    secret          = testing123
    shortname       = ville-dmz
    nas_type        = other
}

client localhost {
    ipaddr          = 127.0.0.1
    secret          = testing123
    shortname       = localhost
    nas_type        = other
}
