include:
  - compose.p0.yml

services:

  step-ca:
    image: smallstep/step-ca
    container_name: step-ca
    environment:
      - DOCKER_STEPCA_INIT_NAME=VilleSousSiege
      - DOCKER_STEPCA_INIT_DNS_NAMES=step-ca
      - DOCKER_STEPCA_INIT_REMOTE_MANAGEMENT=true
      - DOCKER_STEPCA_INIT_PASSWORD=VilleSousSiege2024!
    volumes:
      - step-ca-data:/home/step
    networks:
      - dmz
    restart: unless-stopped

  mtls-server:
    image: nginx:alpine
    container_name: mtls-server
    volumes:
      - mtls-certs:/etc/nginx/certs
      - ./nginx-mtls.conf:/etc/nginx/conf.d/default.conf
    networks:
      - lan
    restart: unless-stopped

  mtls-client:
    image: alpine/curl
    container_name: mtls-client
    command: sleep infinity
    networks:
      - lan
    restart: unless-stopped

volumes:
  step-ca-data:
  mtls-certs:
