networks:
  dmz:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
  lan:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24
  monitoring:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/24
  attacker:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/24

services:

  dvwa:
    image: vulnerables/web-dvwa
    container_name: dvwa
    networks:
      - lan
    restart: unless-stopped

  dvwa-db:
    image: mysql:8.0
    container_name: dvwa-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dvwa
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=p@ssw0rd
    volumes:
      - dvwa-db-data:/var/lib/mysql
    networks:
      - lan
    restart: unless-stopped

  echo-server:
    image: ealen/echo-server
    container_name: echo-server
    networks:
      - lan
    restart: unless-stopped

  kali-lite:
    image: kalilinux/kali-rolling
    container_name: kali-lite
    command: sleep infinity
    networks:
      - attacker
      - lan
    restart: unless-stopped

volumes:
  dvwa-db-data:
