include:
  - compose.p0.yml

services:

  step-ca:
    image: smallstep/step-ca
    container_name: step-ca
    environment:
      - DOCKER_STEPCA_INIT_NAME=VilleSousSiege
      - DOCKER_STEPCA_INIT_DNS_NAMES=step-ca
      - DOCKER_STEPCA_INIT_REMOTE_MANAGEMENT=true
    volumes:
      - step-ca-data:/home/step
    networks:
      - dmz
    restart: unless-stopped

  mtls-client:
    image: alpine/curl
    container_name: mtls-client
    command: sleep infinity
    networks:
      - lan
    restart: unless-stopped

volumes:
  step-ca-data:
